### ISSUE TITLE
Can't download optiboot 7

### ISSUE THREAD

**Issue by deirdreobyrne** [Optiboot/optiboot#245]
You've mixed up your URLs. The json is at https://github.com/Optiboot/optiboot/releases/download/7.0-180815/package_optiboot_optiboot-additional_index.json, the zip is at https://github.com/Optiboot/optiboot/releases/download/7.0-180815/Optiboot-7.0.zip, but the json says the zip is at https://github.com/Optiboot/optiboot/releases/download/v7.0/Optiboot-7.0.zip

Error downloading https://github.com/Optiboot/optiboot/releases/download/v7.0/Optiboot-7.0.zip
java.lang.RuntimeException: java.lang.Exception: Error downloading https://github.com/Optiboot/optiboot/releases/download/v7.0/Optiboot-7.0.zip
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:176)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading https://github.com/Optiboot/optiboot/releases/download/v7.0/Optiboot-7.0.zip
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:131)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:69)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:102)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$1(ContributionManagerUI.java:173)
	... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 404
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:194)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:128)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:129)
	... 4 more

**Comment by Roberto6969** [comment]
It would be great to correct this issue

![screenshot 2018-09-18 10 30 24](https://user-images.githubusercontent.com/21200507/45674774-10d3b600-bb2e-11e8-99c3-740be83d0ee6.png)

**Comment by WestfW** [comment]
Fixed...
